export interface OrderModel {
  groupDesc: string;
  categoryEN: string;
  upcCode: string;
  brand: string;
  descEN1: string;
  itemSize: string;
  itemUnit: string;
  regularPrice: number;
  salePrice: number;
  onHand: number;
  qtySold: number;
  lastSold: string | null;
  receivedQty: number;
  soldSinceLastReceived: number | null;
  receivedDate: string | null;
  vendorID: string;
  aisle: string | null;
  sold7Days: number | null;
  sold30Days: number | null;
  sold90Days: number | null;
  sold180Days: number | null;
  totalWaste: string | null;
  lastWasted: string | null;
  discontinued: number;
}


export const orders: OrderModel[] = [
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Dips',
    upcCode: '850037363322',
    brand: 'HOLY HUMMUS',
    descEN1: 'MED HUMMUS ZAATAT POLIVE OIL 16 OZ',
    itemSize: '16',
    itemUnit: 'OZ',
    regularPrice: 7.49,
    salePrice: 7.49,
    onHand: 0,
    qtySold: 65,
    lastSold: '06/23/25',
    receivedQty: 12,
    soldSinceLastReceived: 10,
    receivedDate: '05/31/25',
    vendorID: 'EAST COAST DELIGHT L',
    aisle: 'MT19',
    sold7Days: 2,
    sold30Days: 15,
    sold90Days: 35,
    sold180Days: 53,
    totalWaste: null,
    lastWasted: null,
    discontinued: 0
  },
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Perishable',
    upcCode: '31285101038',
    brand: "ABRAHAM'S",
    descEN1: 'BABA GHANNOUJ 8 OZ',
    itemSize: '8',
    itemUnit: 'OZ',
    regularPrice: 3.99,
    salePrice: 3.79,
    onHand: 8,
    qtySold: 143,
    lastSold: '06/18/25',
    receivedQty: 24,
    soldSinceLastReceived: 16,
    receivedDate: '5/15/25',
    vendorID: 'EAST COAST DELIGHT L',
    aisle: 'MT19',
    sold7Days: 2,
    sold30Days: 8,
    sold90Days: 37,
    sold180Days: 78,
    totalWaste: null,
    lastWasted: null,
    discontinued: 0
  },
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Dips',
    upcCode: '850037363124',
    brand: 'HOLY HUMMUS',
    descEN1: 'ROASTED RED PEPPER HUMMUS 10 OZ',
    itemSize: '10',
    itemUnit: 'OZ',
    regularPrice: 5.99,
    salePrice: 4.99,
    onHand: 1,
    qtySold: 77,
    lastSold: '06/13/25',
    receivedQty: 12,
    soldSinceLastReceived: 12,
    receivedDate: '05/15/25',
    vendorID: 'EAST COAST DELIGHT L',
    aisle: 'MT19',
    sold7Days: null,
    sold30Days: 11,
    sold90Days: 35,
    sold180Days: 58,
    totalWaste: null,
    lastWasted: null,
    discontinued: 0
  },
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Perishable',
    upcCode: '31285101045',
    brand: "ABRAHAM'S",
    descEN1: 'HUMMOS, ROASTED GARLIC 8 OZ',
    itemSize: '8',
    itemUnit: 'OZ',
    regularPrice: 3.99,
    salePrice: 3.79,
    onHand: 13,
    qtySold: 150,
    lastSold: '06/21/25',
    receivedQty: 24,
    soldSinceLastReceived: 11,
    receivedDate: '05/31/25',
    vendorID: 'EAST COAST DELIGHT L',
    aisle: 'MT19',
    sold7Days: 6,
    sold30Days: 11,
    sold90Days: 34,
    sold180Days: 71,
    totalWaste: null,
    lastWasted: null,
    discontinued: 0
  },
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Perishable',
    upcCode: '810583042904',
    brand: 'POWER FU',
    descEN1: 'POWER-FU SALAD SANDWICH 7.5 OZ',
    itemSize: '7.5',
    itemUnit: 'OZ',
    regularPrice: 4.49,
    salePrice: 4.49,
    onHand: 0,
    qtySold: 0,
    lastSold: null,
    receivedQty: 0,
    soldSinceLastReceived: null,
    receivedDate: null,
    vendorID: 'EAST COAST DELIGHT L',
    aisle: null,
    sold7Days: null,
    sold30Days: null,
    sold90Days: null,
    sold180Days: null,
    totalWaste: null,
    lastWasted: null,
    discontinued: 0
  },
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Dips',
    upcCode: '850037363025',
    brand: 'HOLY HUMMUS',
    descEN1: 'JERUSALEN CLASSIC HUMMUS 10 OZ',
    itemSize: '10',
    itemUnit: 'OZ',
    regularPrice: 5.19,
    salePrice: 4.99,
    onHand: 11,
    qtySold: 169,
    lastSold: '06/23/25',
    receivedQty: 12,
    soldSinceLastReceived: 10,
    receivedDate: '05/31/25',
    vendorID: 'EAST COAST DELIGHT L',
    aisle: 'MT19',
    sold7Days: 3,
    sold30Days: 17,
    sold90Days: 53,
    sold180Days: 83,
    totalWaste: null,
    lastWasted: null,
    discontinued: 0
  },
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Dips',
    upcCode: '850037363094',
    brand: 'HOLY HUMMUS',
    descEN1: 'SMOOTH & CREAMY RTD PEP HUMMUS 16 OZ',
    itemSize: '16',
    itemUnit: 'OZ',
    regularPrice: 7.49,
    salePrice: 7.49,
    onHand: 0,
    qtySold: 0,
    lastSold: null,
    receivedQty: 0,
    soldSinceLastReceived: null,
    receivedDate: null,
    vendorID: 'EAST COAST DELIGHT L',
    aisle: null,
    sold7Days: null,
    sold30Days: null,
    sold90Days: null,
    sold180Days: null,
    totalWaste: null,
    lastWasted: null,
    discontinued: 0
  },
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Dips',
    upcCode: '850037363308',
    brand: 'HOLY HUMMUS',
    descEN1: 'HUMMUS TAHINI 10 OZ',
    itemSize: '10',
    itemUnit: 'OZ',
    regularPrice: 5.39,
    salePrice: 4.99,
    onHand: 0,
    qtySold: 58,
    lastSold: '06/22/25',
    receivedQty: 12,
    soldSinceLastReceived: 12,
    receivedDate: '05/01/25',
    vendorID: 'EAST COAST DELIGHT L',
    aisle: 'MT19',
    sold7Days: 4,
    sold30Days: 9,
    sold90Days: 12,
    sold180Days: 19,
    totalWaste: '8',
    lastWasted: '1/11/25',
    discontinued: 0
  },
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Perishable',
    upcCode: '810583004445',
    brand: "ABRAHAM'S",
    descEN1: 'VEGI CHICKEN SALAD SANDWICH 7.5 OZ',
    itemSize: '7',
    itemUnit: 'OZ',
    regularPrice: 3.99,
    salePrice: 3.99,
    onHand: 0,
    qtySold: 0,
    lastSold: null,
    receivedQty: 0,
    soldSinceLastReceived: null,
    receivedDate: null,
    vendorID: 'EAST COAST DELIGHT L',
    aisle: null,
    sold7Days: null,
    sold30Days: null,
    sold90Days: null,
    sold180Days: null,
    totalWaste: null,
    lastWasted: null,
    discontinued: -1
  },
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Dips',
    upcCode: '850037363056',
    brand: 'HOLY HUMMUS',
    descEN1: 'TRADITIONAL CLASSIC HUMMUS 16 OZ',
    itemSize: '16',
    itemUnit: 'OZ',
    regularPrice: 7.39,
    salePrice: 7.39,
    onHand: 0,
    qtySold: 0,
    lastSold: null,
    receivedQty: 0,
    soldSinceLastReceived: null,
    receivedDate: null,
    vendorID: 'EAST COAST DELIGHT L',
    aisle: null,
    sold7Days: null,
    sold30Days: null,
    sold90Days: null,
    sold180Days: null,
    totalWaste: null,
    lastWasted: null,
    discontinued: 0
  },
  {
    groupDesc: 'Refrigerated foods',
    categoryEN: 'Ref, Beverages',
    upcCode: '810487003308',
    brand: 'HEAVEN & EARTH',
    descEN1: 'POMEGRANATE JUICE ORGANIC 11.15 OZ',
    itemSize: '11.15',
    itemUnit: 'FLOZ',
    regularPrice: 4.59,
    salePrice: 4.39,
    onHand: 0,
    qtySold: 46,
    lastSold: '01/18/25',
    receivedQty: 12,
    soldSinceLastReceived: 18,
    receivedDate: '10/18/24',
    vendorID: 'EAST COAST DELIGHT L',
    aisle: 'MT3',
    sold7Days: null,
    sold30Days: null,
    sold90Days: 8,
    sold180Days: null,
    totalWaste: null,
    lastWasted: null,
    discontinued: 0
  },
  // (continúa con el resto de los objetos en el mismo formato...)
];
